config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: 'users/confirmations', omniauth_callbacks: "users/omniauth_callbacks" }
  

  root "static_pages#home"
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  get 'contacts', to: 'static_pages#contacts'
  get 'admin', to: 'static_pages#admin'
  get 'stats', to: 'static_pages#stats'
  
  devise_scope :user do
    get "business", to: "users/registrations#new_bus"
    get "prosignup", to: "users/registrations#new_pro"
    get 'signup', to: 'users/registrations#new_bus'
    get '/auth/facebook/callback', to: 'users/sessions#create'
    get '/users/auth/facebook/callback', to: 'users/sessions#create'
    get '/auth/linkedin/callback', to: 'users/sessions#create'
    get '/users/auth/linkedin/callback', to: 'users/sessions#create'
    get 'login', to: "users/sessions#new"
  end
  
    post 'createpassword', to:'users#createpassword'
  
  

  
  
  resources :users do
    collection do
    end
    member do
      put "like", to: "users#upvote"
      put "dislike", to: "users#downvote"
      get "offer", to: "users#newoffer"
      post "offer", to: "users#createoffer"
      get "acceptoffer", to: "users#acceptoffer"
      get "test", to: "users#new_test"
      post "test", to: "users#create_test"
      get "tests", to: "users#tests", as: :tests
      get "applications", to: "users#applications", as: :applications
    end
  end
  

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :letters, only: [:new, :create, :show]
  post 'sendletter', to: 'letters#create'
  get 'sendletter', to: 'letters#new'
  get 'automate', to: 'letters#automate_new'
  post 'automate', to: 'letters#automate_create'
  get 'automate_show', to: 'letters#automate_show'
  
  get "users/:id/edit_admin", to: "users#edit_admin", as: :edit_user_admin
  post "users/:id/mark_interviewed", to: "users#mark_interviewed", as: :user_mark_interviewed
  
  post 'users', to: 'users#index'
  get "/feed/:query", to: "users#feed"
  post "/feed/:query", to: "users#feed"
  get 'feed', to: 'users#feed'
  post 'feed', to: 'users#feed'
  

  
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get "/404", to: "errors#not_found"
  get "/500", to: "errors#internal_server_error"
  get "*path" => 'errors#not_found'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  http_basic_authenticate_with name: ENV['LOGIN'], password: ENV['PASSWORD'], only: [:admin, :stats]
  rescue_from ActiveRecord::RecordNotFound do |exception|
    redirect_to login_url, :alert => exception.message
  end
  
  def admin
    @users = User.all.order('created_at DESC')
    @votes = ActsAsVotable::Vote.all.order('created_at DESC')
    @tests = Test.all.order('created_at DESC')
  end
  
  def stats
    @users = User.all.order('created_at DESC')
    @votes = ActsAsVotable::Vote.all.order('created_at DESC')
  end
  
  def home
    if current_user then
      redirect_to current_user and return
    else
      redirect_to "/business"
    end
  end
  def signup_pro
    @user = User.new
  end

  def help
  end
  def signup_business
    @user = User.new
  end
  def about
  end
  def contacts
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  include ActionView::Helpers::TextHelper
  def simple_format_nbsp (t, tag = "p")
    return simple_format(t.to_s.gsub(/\s(?<word>\S{1,3})\s/,' \k<word>&nbsp;'), {}, wrapper_tag: tag)
  end
  
end

app/views/static_pages/_adminmenu.html.erb
<div class="container-fluid project-container-header">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <div class="row">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text-left">
          <h1>Admin panel</h1>
          <ul class="list-inline">
            <li><%= link_to "New users and votes history", admin_url%></li>
            <li><%= link_to "View/edit users", users_url %></li>
            <li><%= link_to "View stats", stats_url %></li>
              
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/about.erb
<% provide(:title, "The Globe. Create Anywhere.") %>
<% provide(:description, "Hard to hire skilled talent locally? Meet here with world class pros willing to travel or relocate to your location.") %>
<% provide(:image, root_url + "images/paraglide.jpg") %>
        
<div class="container-fluid project-container-header">
  <div class="row">
    <div class="container">
      <div class="row">
        <div class="col-md-10"> 
          <h1>About The Globe</h1>
          <p></p>
        </div>
      </div>
    </div>  
  </div>           
</div> 
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#business" data-toggle="tab">Business (employer)</a></li>
        <li><a href="#pro" data-toggle="tab">Professional</a></li>
      </ul>
      <div id="abouttab" class="tab-content">
        <div class="tab-pane fade active in" id="business">
          <dl class="dl-horizontal">
            <dt><h3>What it is</h3></dt>
            <dd><p>This is a platform for businesses to source top-notch professionals abroad and bring them in for a limited term collaboration. We serve businesses facing talent shortfalls locally and pros that are willing to travel or relocate to other places. We focus mainly on high level digital pros because of their scarcity, short development cycle and universal applicability of their skills.</p></dd>
            <dt><h3>How it works</h3></dt>
            <dd><p>The first step is signing up and filling up profile data as usual. Sign-up is open for businesses and invitation-only for pros at this stage. Signed in business gets a feed of suggested candidates with detailed information about track record, skills, interests and priorities, as well as external recommendations. Signed-in pro, in a similar manner, gets a feed of suggested roles in companies. When the business and the pro &laquo;like&raquo; each other, we initiate direct communication between them. Once both sides agree on the hire, the platform is used as financial and legal intermediary. After the contract&rsquo;s completion both the company and the pro review each other thus generating history and earning personal trustworthiness on the platform.</p></dd>
            <dt><h3>Who pays</h3></dt>
            <dd><p>We only charge 10% fee from the business side.</p></dd>
            <dt><h3>Is it another freelance platform?</h3></dt>
            <dd><p>Jobs listed here are not permanent / indefinite, thus it is a freelance platform in a way. An important distinction is that we are focusing on higher-level roles that require at least some period of presence on site of the business. Our temporary contract may be viewed as a probation period for permanent job, but there are other benefits of such contract: 
                <ol class="list">
                  <li>it is easier for a pro to try living and working in different countries/industries rather then decide on permanent relocation;</li>
                  <li>t is easier for a company to invite someone on a short contract first, and it is ultimately efficient for irregular tasks and consulting jobs; </li>
                  <li>when a pro uses the platform as legal intermediary, she/he doesn&rsquo;t have to obtain permanent work permit in the country and may enter on business visitor type of visa (which is substantially easier to get).</li>
                </ol></p></dd>
          </dl>
        </div>
        <div class="tab-pane fade" id="pro">
          <p></p>
        </div>
      </div>      
    </div>
  </div>
</div>

app/views/static_pages/admin.html.erb
<div class="flash-alerts">
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type%>"><%= message %></div>
<% end %>	
</div>
<%= render "adminmenu"%>
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h2>Tests</h2>
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Test</th>
            <th>Total</th>
            <th>Created</th>
          </tr>
        </thead>
        <tbody>
        <% @tests.each do |test| %>
          <tr><% user = User.find(test.user_id) %>
            <td><%= user.id.to_s%></td>
            <td><%= user.name%></td>
            <td><%= user.email%></td>
            <td><%= test.num%></td>
            <td><%= test.total%> of <%= test.maxtotal %></td>
            <td><%= user.created_at.to_s%></td>
          </tr>
        <% end%>
        </tbody>
      </table>
      
      <h2>New users</h2>
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>id</th>
            <th>Email</th>
            <th>Type</th>
            <th>Skills</th>
            <th>Created</th>
            <th>Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id.to_s%></td>
            <td><%= user.email%></td>
            <td><%= if user.utype == 1 then "Company" else "Pro" end%></td>
            <td><%= user.skills.to_s%></td>
            <td><%= user.created_at.to_s%></td>
            <td><%= user.status.to_s%></td>
            <td><%=link_to "Mark interviewed", user_mark_interviewed_url(user.id), method: "post"%><br>
                <%=link_to "Show", user_url(user) %><br>
                <%=link_to "Edit", edit_user_admin_url(user.id) %><br>
                <%= link_to('Destroy', user, method: "delete", data: { confirm: 'Are you sure?', disable_with: 'loading...' }) %></td>
          </tr>
        <% end%>
        </tbody>
      </table>
    </div>
    <div class="col-sm-12">
      <h2>Likes</h2>
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>Sender, id</th>
            <th>email</th>
            <th>Receiver, id</th>
            <th>email</th>
            <th>Time</th>
          </tr>
        </thead>
        <tbody>
        <% @votes.each do |vote| %>
          <tr>
            <td><%= vote.voter_id.to_s%></td>
            <td><%= if User.find(vote.voter_id) then User.find(vote.voter_id).email end%></td>
            <td><%= vote.votable_id.to_s%></td>
            <td><%= if User.find(vote.votable_id) then User.find(vote.votable_id).email end%></td>
            <td><%= vote.created_at.to_s%></td>
          </tr>
        <% end%>
        </tbody>
      </table>
    </div>
  </div>
  
</div>

app/views/static_pages/contacts.erb
<% provide(:title, "The Globe. Create Anywhere.") %>
<% provide(:description, "Hard to hire skilled talent locally? Meet here with world class pros willing to travel or relocate to your location.") %>
<% provide(:image, root_url + "images/paraglide.jpg") %>

<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 project-features">
      <br><br>
      <h2>Contacts.</h2>
      <p>With all inqueries please contact Irina at irina.e.nazarova@gmail.com</p>
    </div>
  </div>
  <div class="row">
    
  </div>
</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/sendmail.erb
<% provide(:title, "The Globe. Create Anywhere.") %>
<% provide(:description, "Hard to hire skilled talent locally? Meet here with world class pros willing to travel or relocate to your location.") %>
<% provide(:image, root_url + "images/paraglide.jpg") %>
        
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3 about-text">
      <br><Br>
      <h1>About us</h1>
      <h3>What it is.</h3>
      <p>We&nbsp;are building a&nbsp;platform for companies to&nbsp;find and hire top-notch pros from overseas. We&nbsp;serve businesses facing talent shortfalls locally and pros that are willing to&nbsp;travel or&nbsp;relocate to&nbsp;other places. We&nbsp;focus mainly on&nbsp;high level digital pros because of&nbsp;their scarcity, short development cycle and universal applicability of&nbsp;their skills.</p>
      <h3>How it works.</h3>
      <p>The first step is&nbsp;signing up&nbsp;and filling up&nbsp;profile data as&nbsp;usual. Sign-up is&nbsp;open for businesses and invitation-only for pros at&nbsp;this stage. Signed in&nbsp;business gets a&nbsp;feed of&nbsp;suggested candidates with detailed information about track record, skills, interests and priorities, as&nbsp;well as&nbsp;external recommendations. Signed-in pro, in&nbsp;a&nbsp;similar manner, gets a&nbsp;feed of&nbsp;suggested roles in&nbsp;companies. When the business and the pro &laquo;like&raquo; each other, we&nbsp;initiate direct communication between them. Once both sides agree on&nbsp;the hire, the platform is&nbsp;used as&nbsp;financial and legal intermediary. After the contract&rsquo;s completion both the company and the pro review each other thus generating history and earning personal trustworthiness on&nbsp;the platform.</p>
      <h3>Who pays.</h3>
      <p>We&nbsp;only charge&nbsp;10%&nbsp;fee from the&nbsp;business side.</p>
      <h3>Is it another freelance platform?</h3>
      <p>Jobs listed here are not permanent&nbsp;/ indefinite, thus it&nbsp;is&nbsp;a&nbsp;freelance platform in&nbsp;a&nbsp;way. An&nbsp;important distinction is&nbsp;that we&nbsp;are focusing on&nbsp;higher-level roles that require at&nbsp;least some period of&nbsp;presence on&nbsp;site of&nbsp;the business. Our temporary contract may be&nbsp;viewed as&nbsp;a&nbsp;probation period for permanent job, but there are other benefits of&nbsp;such contract: 
      <ol><li>it&nbsp;is&nbsp;easier for a&nbsp;pro to&nbsp;try living and working in&nbsp;different countries/industries rather then decide on&nbsp;permanent relocation;</li><li>t&nbsp;is&nbsp;easier for a&nbsp;company to&nbsp;invite someone on&nbsp;a&nbsp;short contract first, and it&nbsp;is&nbsp;ultimately efficient for irregular tasks and consulting jobs; </li><li>when a&nbsp;pro uses the platform as&nbsp;legal intermediary, she/he doesn&rsquo;t have to&nbsp;obtain permanent work permit in&nbsp;the country and may enter on&nbsp;business visitor type of&nbsp;visa (which is&nbsp;substantially easier to&nbsp;get).</li></ol></p>
    </div>
  </div>
</div>

<div class="container-fluid subscribe-form">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <p>Subscribe to receive our latest news.</p>
        <!-- Begin MailChimp Signup Form -->
        <div id="mc_embed_signup">
          <form action="//createanywhe.us12.list-manage.com/subscribe/post?u=bea15e00ae5d4fd8f32002b3b&amp;id=ac20c1484c" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
            <div id="mc_embed_signup_scroll">
              <div class="mc-field-group">
              	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL" placeholder="Enter your email"> <input type="submit" value="Go" name="subscribe" id="mc-embedded-subscribe" class="button">
              </div>
            	<div id="mce-responses" class="clear">
            		<div class="response" id="mce-error-response" style="display:none"></div>
            		<div class="response" id="mce-success-response" style="display:none"></div>
            	</div>    
            	<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
              <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_bea15e00ae5d4fd8f32002b3b_ac20c1484c" tabindex="-1" value=""></div>
              
            </div>
          </form>
        </div>
        <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
        <!--End mc_embed_signup-->
      </div>
    </div>
  </div>
</div>
      

app/views/static_pages/signup_business.erb
<% provide(:title, "The Globe. Create Anywhere.") %>
<% provide(:description, "Hard to hire skilled talent locally? Meet here with world class pros willing to travel or relocate to your location.") %>
<% provide(:image, root_url + "images/paraglide.jpg") %>

<div class="site-wrapper site-wrapper-project">
  <div class="site-wrapper-inner">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type%>"><%= message %></div>
    <% end %>	
    <div class="cover-container cover-container-project">
      <div class="inner cover">
        <center><%= simple_format_nbsp("Bring talent from around the globe", "h1") %>
        <%= simple_format_nbsp("Hard to hire skilled talent locally? Meet here with high profile web/ mobile engineers willing to travel to your location.") %>
        <%= link_to "Sign up to invite talent", "#signup", class: "btn btn-lg btn-primary" %></center>
        
      </div>
    </div>
  </div>
</div>
<div class="container container-white">
  <div class="row">
    <div class="col-sm-5">
    </div>
    <div class="col-sm-7">
      <h1>Invite better talent today</h1>
      <%= simple_format_nbsp("Experienced, productive & high profile talent has always been scarce. And if you also seek genuine interest, determination and efficient communication within the team, you need no artificial borders between you and your perfect match. <span class='text-primary'>We are here to introduce you to inspired and experienced pros from around the world, willing to travel to your location and build great products with you.</span>") %>
      <%= simple_format_nbsp("Rockstar web and mobile engineers, architects and other high profile pros today seek to engage in inpiring projects around the world, explore cultures and teams, choose where in the world to work next and where to stay longer. We build the platform to empower them.") %>
      <%= simple_format_nbsp("Also we are set to relax the key obstacle on the way of talent mobility: work permits. We legally support contracts with duration up to 6 months. With its pros and cons, temporary contracts are efficient, flexible, and expose you to a vast amount of top-notch talent, otherwise unaccessible.") %>
      <%= link_to "Become a part of The Globe", "#signup", class: "btn btn-lg btn-primary" %>
    </div>
  </div>
</div>
<div class="container-fluid signup-bluegreen-container">
  <div class="row">
    <div class="container">
      <div class="row">
        <div class="col-md-12 project-features">
          <%= simple_format_nbsp("Unlock the new source of growth","h2") %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 project-features"> 
        <%= simple_format_nbsp("Get your tasks done by global pros", "h3") %>
        <p><%= simple_format_nbsp("Need to build an MVP, or an app, set up analytics or architecture? Bring in a high profile pro from abroad. Meet here with top-notch pros willing to travel or relocate to your place, engage them in your inspiring project and get your tasks done.") %></p>
        </div>
        <div class="col-md-4 project-features">
        <%= simple_format_nbsp("We handle visas and work permits", "h3") %>
        <p><%= simple_format_nbsp("We&nbsp;function as&nbsp;a&nbsp;global consulting agency with pros traveling to&nbsp;your location on&nbsp;behalf of&nbsp;our&nbsp;company, which in&nbsp;most cases releases you&nbsp;from visa sponsorship need.") %></p>
        </div>
        <div class="col-md-4 project-features">
        <%= simple_format_nbsp("Open your doors to global tech community", "h3") %>
        <p><%= simple_format_nbsp("Enrich your team's expertise and&nbsp;culture by&nbsp;mixing up&nbsp;with talent from around the&nbsp;globe. Bring in people inspired to contribute to your goal, to experience working with your team and in your industry. Meet and befriend passionate pros and great people.") %></p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="form-group" id="user_form"> 
  <input type="text" name="prevent_autofill" id="prevent_autofill" value="" style="display:none;" />
  <input type="password" name="password_fake" id="password_fake" value="" style="display:none;" />

  <a name="signup"></a>
  <%= form_for @user, url: 'business#signup' do |f| %>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <h1>Sign up in only 2 steps</h1>
          <h3>1. Choose skills you&nbsp;need</h3>
          <p>You can change it&nbsp;later on&nbsp;your personal page.</p>
          <ul class="list-inline">
            <% $globalvar_skills.each do |skill|%>
              <% if @user.skills && @user.skills[skill] == "on" then checkline="checked" else checkline =""  end%>
              <li class="project-skills-edit">
                <input class="form-control" type="checkbox" name="user[skills][<%=skill%>]" id="<%=skill%>" <%=checkline%> >
                <label for="<%=skill%>"><%=skill%></label>
              </li>
            <%end%>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-info">
              <%= message %>
            </div>
          <% end %>
          <h3>2. Fill in contact details</h3>
          <p>We will contact your shortly to discuss the details.</p>
          <%= f.hidden_field :utype, value: 1 %>
          
          <div class="form-group">
            <%= f.text_field :name, placeholder: "Company name", class: "form-control", autocomplete: "false", autofill: "false"%>
          </div>
          <% if @user.errors[:name].any? %>
            <div class="alert alert-warning" role="alert">
              <%= "Company name is needed here." %>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.password_field :password, placeholder: "Create a password (longer than 5 chars)", class: "form-control", autocomplete: "false", autofill: "false" %>
          </div>
          <%if @user.errors[:password].any?%>
            <div class="alert alert-warning">
              <%= @user.errors[:password].first.to_s %>
            </div>
          <%end%>
          
          <div class="form-group">
            <%= f.text_field :firstname, placeholder: "Your name", class: "form-control", autocomplete: "false", autofill: "false" %>
          </div>
          <% if @user.errors[:firstname].any? %>
            <div class="alert alert-warning" role="alert">
              <%= @user.errors[:firstname].first %>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.email_field :email, placeholder: "Your work email", class: "form-control" %>
          </div>
          <% if @user.errors[:email].any? %>
            <div class="alert alert-warning" role="alert">
              <%= @user.errors[:email].first %>
            </div>
          <% end %>
          <div class="form-group">
            <%= f.url_field :website, placeholder: "Company website", class: "form-control" %>
          </div>
          <%= f.submit "Submit", class: "btn btn-lg btn-success" %>
        </div>
      </div>
    </div> 
  <%end%>
</div>


<div class="container container-white no-background">
  <div class="row">
    <div class="col-md-7">
      <h1><small>How it works</small><br>
        Recruit global pros</h1>
      <%= simple_format_nbsp("The Globe allows you to search and contact high profile web/mobile developers and other digital pros. We pre-screen pros and projects and serve as a guarantor for both sides.") %>
      <%= simple_format_nbsp("") %>
      <%= simple_format_nbsp("As the employer you only pay the platform 10% of the contract value for the successful collaboration.") %>
    </div>
    <div class="col-md-5">
      <br><br>
      <%= simple_format_nbsp("The process of engaging a pro", "h4") %>
      <ul class="list-inline process-items">
        <li>1. Review the pro's profile</li>
        <li>2. Invite to chat</li>
        <li>3. Interview over skype</li>
        <li>4. Extend an offer</li>
        <li>5. Collaborate up to 6M in your office</li>
        <li>6. Switch to long-term, continue remotely or finish</li>
        <li>7. Review each other</li>
      </ul>
      
    </div>
    <div class="col-md-12">
      
      <%= link_to "Join The Globe", "#signup", class: "btn btn-lg btn-primary" %>
    </div>
    
  </div>
</div>

app/views/static_pages/stats.html.erb
<%= render "adminmenu"%>
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h2>User retention</h2>
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>id</th>
            <th>Email</th>
            <th>Type</th>
            <th>Skills</th>
            <th>Created</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id.to_s%></td>
            <td><%= user.email%></td>
            <td><%= if user.utype == 1 then "Company" else "Pro" end%></td>
            <td><%= user.skills_string.to_s%></td>
            <td><%= user.created_at.to_s%></td>
            <td><%=link_to "Show", user_url(user) %><br>
                <%=link_to "Edit", edit_user_admin_url(user.id) %><br>
                <%= link_to('Destroy', user, method: "delete", data: { confirm: 'Are you sure?', disable_with: 'loading...' }) %></td>
          </tr>
        <% end%>
        </tbody>
      </table>
    </div>
    <div class="col-sm-12">
      <h2>Likes</h2>
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>Sender, id</th>
            <th>email</th>
            <th>Receiver, id</th>
            <th>email</th>
            <th>Time</th>
          </tr>
        </thead>
        <tbody>
        <% @votes.each do |vote| %>
          <tr>
            <td><%= vote.voter_id.to_s%></td>
            <td><%= if User.find(vote.voter_id) then User.find(vote.voter_id).email end%></td>
            <td><%= vote.votable_id.to_s%></td>
            <td><%= if User.find(vote.votable_id) then User.find(vote.votable_id).email end%></td>
            <td><%= vote.created_at.to_s%></td>
          </tr>
        <% end%>
        </tbody>
      </table>
    </div>
  </div>
  
</div>