config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: 'users/confirmations', omniauth_callbacks: "users/omniauth_callbacks" }
  

  root "static_pages#home"
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  get 'contacts', to: 'static_pages#contacts'
  get 'admin', to: 'static_pages#admin'
  get 'stats', to: 'static_pages#stats'
  
  devise_scope :user do
    get "business", to: "users/registrations#new_bus"
    get "prosignup", to: "users/registrations#new_pro"
    get 'signup', to: 'users/registrations#new_bus'
    get '/auth/facebook/callback', to: 'users/sessions#create'
    get '/users/auth/facebook/callback', to: 'users/sessions#create'
    get '/auth/linkedin/callback', to: 'users/sessions#create'
    get '/users/auth/linkedin/callback', to: 'users/sessions#create'
    get 'login', to: "users/sessions#new"
  end
  
    post 'createpassword', to:'users#createpassword'
  
  

  
  
  resources :users do
    collection do
    end
    member do
      put "like", to: "users#upvote"
      put "dislike", to: "users#downvote"
      get "offer", to: "users#newoffer"
      post "offer", to: "users#createoffer"
      get "acceptoffer", to: "users#acceptoffer"
      get "test", to: "users#new_test"
      post "test", to: "users#create_test"
      get "tests", to: "users#tests", as: :tests
      get "applications", to: "users#applications", as: :applications
    end
  end
  

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :letters, only: [:new, :create, :show]
  post 'sendletter', to: 'letters#create'
  get 'sendletter', to: 'letters#new'
  get 'automate', to: 'letters#automate_new'
  post 'automate', to: 'letters#automate_create'
  get 'automate_show', to: 'letters#automate_show'
  
  get "users/:id/edit_admin", to: "users#edit_admin", as: :edit_user_admin
  post "users/:id/mark_interviewed", to: "users#mark_interviewed", as: :user_mark_interviewed
  
  post 'users', to: 'users#index'
  get "/feed/:query", to: "users#feed"
  post "/feed/:query", to: "users#feed"
  get 'feed', to: 'users#feed'
  post 'feed', to: 'users#feed'
  

  
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get "/404", to: "errors#not_found"
  get "/500", to: "errors#internal_server_error"
  get "*path" => 'errors#not_found'
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  def show
    super do |resource|
      sign_in(resource)
      resource.status = 1
      resource.save
      flash[:success] = "You are logged in. Please fill in your profile data."
      redirect_to edit_user_path(resource) and return
    end
  end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  require 'uuidtools'

  def facebook
    oauthorize "Facebook"
  end

  def linkedin
    oauthorize "LinkedIn"
  end

  def passthru
    redirect_to "/404"
  end

private

  def oauthorize(kind)
    puts "uauthorize " + kind.to_s + " " + env["omniauth.auth"].to_s
    @user = find_for_ouath(kind, env["omniauth.auth"], current_user)
    puts "user = " + @user.name
    if @user
      puts "success "
      
      puts env["omniauth.auth"].to_s
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => kind
      session["devise.#{kind.downcase}_data"] = env["omniauth.auth"]
      sign_in_and_redirect @user, :event => :authentication
    end
  end

  def find_for_ouath(provider, access_token, resource=nil)
    user, email, name, uid, auth_attr = nil, nil, nil, {}
    case provider
      when "Facebook"
        uid = access_token['uid']
        email = access_token['info']['email']
        auth_attr = { :uid => uid, :token => access_token['credentials']['token'],
          :secret => nil, :first_name => access_token['info']['first_name'],
          :last_name => access_token['info']['last_name'], :name => access_token['info']['name'],
          :link => access_token['extra']['raw_info']['link'] }
      when 'LinkedIn'
        uid = access_token['uid']
        name = access_token['info']['name']
        auth_attr = { :uid => uid, :token => access_token['credentials']['token'],
          :secret => access_token['credentials']['secret'], :first_name => access_token['info']['first_name'],
          :last_name => access_token['info']['last_name'],
          :location => access_token['info']['location'],
          :link => access_token['info']['urls']['public_profile'] }
    else
      raise 'Provider #{provider} not handled'
    end
    if resource.nil?
      if email
        user = find_for_oauth_by_email(email, resource)
      elsif uid && name
        user = find_for_oauth_by_uid(uid, resource)
        if user.nil?
          user = find_for_oauth_by_name(name, resource)
        end
      end
    else
      user = resource
    end

    auth = user.authorizations.find_by_provider(provider)
    if auth.nil?
      auth = user.authorizations.build(:provider => provider)
      user.authorizations << auth
    end
    auth.update_attributes auth_attr
    if auth_attr[:first_name]&&!auth_attr[:first_name].empty?&&auth_attr[:last_name]&&!auth_attr[:last_name].empty? then
      user.name = auth_attr[:first_name].to_s + " " + auth_attr[:last_name].to_s
    end
    if auth_attr[:link] && !auth_attr[:link].empty? then
      user.linkedin_link = auth_attr[:link]
    end 
    if auth_attr[:location] && !auth_attr[:location].empty? then
      user.location = auth_attr[:location]
    end 
    user.save
    return user
  end

  def find_for_oauth_by_uid(uid, resource=nil)
    user = nil
    if auth = Authorization.find_by_uid(uid.to_s)
      user = auth.user
    end
    return user
  end

  def find_for_oauth_by_email(email, resource=nil)
    if user = User.find_by_email(email)
      user
    else
      user = User.new(:email => email, :password => Devise.friendly_token[0,20])
      user.save
    end
    return user
  end

  def find_for_oauth_by_name(name, resource=nil)
    if user = User.find_by_name(name)
      user
    else
      first_name = name
      last_name = name
      user = User.new(:first_name => first_name, :last_name => last_name, :password => Devise.friendly_token[0,20], :email => "#{UUIDTools::UUID.random_create}@host")
      user.save(:validate => false)
    end
    return user
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]


  def new_bus
    build_resource({})
    set_minimum_password_length
    yield resource if block_given?
    respond_with self.resource
  end
  
  
  def new_pro
    build_resource({})
    set_minimum_password_length
    yield resource if block_given?
    respond_with self.resource
  end


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
   def create
    sign_out
    build_resource(sign_up_params)
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        puts "resource not active"
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      puts "resource not persisted"
      clean_up_passwords resource
      set_minimum_password_length
      if resource.utype == 0 then 
        render 'new_pro'
      else
        render 'new_bus'
      end
    end
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.for(:sign_up) << :utype
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
     edit_user_path(resource)
   end

  # The path used after sign up for inactive accounts.
   def after_inactive_sign_up_path_for(resource)
     new_user_session_path
   end
end

app/helpers/users_helper.rb
module UsersHelper
  $globalvar_skills = ["fullstack", "frontend", "backend", "techlead", "it engineer", "highload", "ruby on rails", "responsive", "sass", "javascript", "jquery", "ajax", "angularjs", "reactjs", "python", "php", "perl", "magento", "ios", "swift", "objective c", "android", "xamarin", "scala", "dotnet", "java", "C/C++", "mysql", "postresql", "sphinx", "redis", "kendo", "api", "sap",  "sql", "erp", "machine learning", "big data", "hadoop", "mapreduce", "amazonws", "data science", "web design", "ux ui design", "graphic design", "product design", "illustration", "photo", "video", "web analytics", "business analytics", "product management", "scrum", "bizdev", "financial modeling", "growth hacking", "market analytics", "git", "mongo db", "neural networks", "deep learning", "django", "nodejs", "opengl", "flux", "backbonejs", "NLP", "golang", "docker"].sort
  
  $globalvar_test = [
    [0, "iOS & Objective C", 300, [2,3,2,4,2,3,4,4],
      [["What is the difference between accessing a property via self or underscore (_)?", 
        ["Underscore triggers KVO",
        "Self triggers getter and setter",
        "Underscore is preferrable and should be used every time",
        "There is no difference"]], 
      ["What is the difference between weak and strong references?", 
        ["Weak creates and changes a copy of the object",
        "Weak reference cannot override value of the object as long as a strong reference exist",
        "Weak reference will be set to null automatically when all strong references are destroyed",
        "Only one strong reference can exist for each object simultaneously"]], 
      ["We have three objects: a grandparent, parent and child. The grandparent retains the parent, the parent retains the child and the child retains the parent. The grandparent releases the parent, what happens? (No other references exist.)", 
        ["The parent is destroyed, the child remains",
        "Both the parent and the child remain",
        "All three objects are destroyed",
        "Only the child is destroyed"]], 
      ["What is method swizzling?", 
        ["Changing implementation of a standard method",
        "Checking if the method is available",
        "Checking if the method is overriden",
        "Changing implementation of a standard selector"]], 
      ["What is ARC?", 
        ["Automatic Reference Changing",
        "Automatic Reference Counting",
        "Automatic Reference Cleaning",
        "Automatic Reference Cooling"]], 
      ["What is NOT a part of the Core Data Stack?", 
        ["The managed object model",
        "The managed object context",
        "The persistent store model",
        "The persistent store coordinator"]], 
      ["dispatch_once ...", 
        ["... destroys the object but keeps its children alive",
        "... sends a request",
        "... creates an object without a token",
        "... is a method from GCD"]], 
      ["What is the difference between @dynamic and @synthesize?", 
        ["@synthesize tells the compiler that the getter and setter methods are not implemented",
        "@synthesize tells the compiler that the getter and setter methods are implemented by a superclass",
        "@dynamic tells the compiler that the getter and setter methods are implemented by the class itself",
        "@dynamic tells the compiler that the getter and setter methods are implemented not by the class itself, but somewhere outside"]]]
    ],
    
    [1, "iOS & Objective C - 2", 300, [2,3,1,3,4,4,2,3],
      [["Which is typically used to avoid Retain Cycles?", 
        ["Strong attribute in a reference to a parent",
        "Weak attribute in a reference to a parent",
        "Copy attribute in a reference to a parent",
        "Strong attribute in a reference to a child"]], 
      ["Which is the reason for declaring a Category instead of a Subclass?", 
        ["To use methods from the original class",
        "To override methods from the original class",
        "To add new methods to all instances of the original class",
        "There is no reason"]], 
      ["What is true about the difference between a Category and a Class Extension?", 
        ["A Class Extention can only be added to a class that is compiled at the same time as the Extention",
        "A Category is just an anonymous Class Extention",
        "A Category can add its own properties and instance variables to a class, while a Class Extention cannot",
        "There are no differences"]], 
      ["Which statement is true about views?", 
        ["Your view may have any number of superviews",
        "Sibling views may not overlap each other in iOS",
        "When the content of a view changes, it is your responsibility to notify the system that your view needs to be redrawn",
        "Block-based animations are available only in iOS 7 and later"]], 
      ["What is true about the Size Classes?", 
        ["A class is a Size Class if all its instances take up the same space in memory",
        "Size Classes are large data sctructures that take up substantial memory",
        "There is no such thing as Size Classes",
        "Size Classes enable developers to stop thinking in terms of specific devices and their screen sizes"]], 
      ["What is true about @autorelease?", 
        ["Autorelease fully automatically manages memory allocation issues",
        "Your code may send an autorelease message outside of its autorelease pool block",
        "For a given autorelease message, the release message is sent immediately, not at the end of the autorelease pool block",
        "When you create a large number of temporary objects that you want to dispose of more quickly, you should create your own autorelease pool block"]], 
      ["What best describes a Managed Object Context?", 
        ["A Managed Object Context is an unique object that stores all instances of your app's Managed Objects",
        "A Managed Object instance exists in one and only one Context, but multiple copies of an Object can exist in different Contexts",
        "A Managed Object Context stores unedited copies of instances of Managed Objects loaded from a Persistent Store",
        "A Managed Object Context is any collection of Managed Objects"]], 
      ["What is true about multithreading in iOS?", 
        ["Creating a new thread is relatively cheap in iOS as it does not require any interactions with the kernel",
        "Cocoa framework by default creates locks and other forms of internal synchronization even for single-threaded applicaionts, degrading their performance",
        "In iOS and OS X v10.5 and later, all objects have the ability to spawn a new thread and use it to execute one of their methods",
        "A detached thread means that the thread’s resources will not be reclaimed by the system when the thread exits, and that you have to take cake of this yourself"]]]
    ]
  ]
  
  def check_connection(provider)
    if current_user.has_connection_with(provider)
      html = ""
    else
      html = link_to user_omniauth_authorize_path(provider: provider.downcase), class: "#{provider}-connect" do
        content_tag :span, 'Connect with ' + provider.to_s, class: "un-verified"
      end
    end
  end
end

app/views/users/_business_details.html.erb
<!-- local vars: usr, _admin-->
  <div class="row">
    <div class="col-sm-9 text-left main-description">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%=link_to usr do %><% if (usr.picture && !usr.picture.empty?) %><img src="<%=usr.picture%>" class="img-responsive" title="<%=usr.name%> @ The Globe." alt="<%=usr.name%> @ The Globe."><%else %><img src="<%=root_url + 'images/paraglide.jpg'%>" class="img-responsive"><%end%><%end%>
          <br>
          <%= render "likes", l_user: usr %>
          <br>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <%if usr.values then%>
          <h2>About us</h2>
            <p><%= simple_format(usr.values) %></p>
          <%end%>
          <%if usr.experience then%>
          <h2>Open Roles</h2>
            <p><%= simple_format(usr.experience) %></p>
          <%end%>
        </div>
      </div>
    </div>
    <div class="col-sm-3 text-left profile-right-panel">
      
      <ul class="list-unstyled">
        <p>Check out our website</p>
        <%if usr.website&&!usr.website.empty?%><li><%= link_to usr.website.to_s, usr.website, target: '_blank'%></li><%end%>
        
        <%if usr.linkedin_link%>
          <p>Founder's Linkedin profile</p>
          <li><%= link_to usr.linkedin_link.to_s, usr.linkedin_link, target: '_blank'%></li><%end%>
        <%if usr.location%>
          <p>Our location</p>
          <li><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> <%= usr.location%></li><%end%>
      </ul>
      <%if _admin then %>
        status: <%= usr.status.to_s %><br>
        <%=link_to "Mark interviewed", user_mark_interviewed_url(usr.id), method: "post"%><br>
        <%=link_to "Show", user_url(usr) %><br>
        <%=link_to "Edit", edit_user_admin_url(usr.id) %><br>
        <%= link_to('Destroy', usr, method: "delete", data: { confirm: 'Are you sure?', disable_with: 'loading...' }) %>
      <%end%>
    </div>
  
  </div>

app/views/users/edit.html.erb
<% provide(:title, "Edit profile") %>

<br><br>
<h1>Edit profile</h1>
<br>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for(@user, id: "person_edit") do |f| %>

      <%= f.email_field :email, placeholder: "Email", class: 'form-control login-form-control' %>

      <%= f.password_field :password, placeholder: "Password", class: 'form-control login-form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Join ( Globe ) now!", signup_path %></p>
  </div>
</div>

<%= link_to 'Return without saving', user_path %>

app/views/users/editperson.html.erb
<% provide(:title, "Edit profile: " + @user.name.to_s + " @ The Globe. Create Anywhere.") %>
<% provide(:description, @user.summary) %>
<% provide(:image, if @user.picture then @user.picture else root_url + "images/paraglide.jpg" end) %>

<%= form_for(@user, html: { id: "person_edit", class: 'directUpload form-horizontal', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
<div class="container-fluid project-container-header">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type%>"><%= message %></div>
  <% end %>	
  <div class="container">
    <div class="col-sm-12 project-container-text text-left">
      <h2>Edit personal information</h2>
      <br><br>
    </div>
  </div>
</div>
<br>
<div class="container-fluid profile-private-info">
  <div class="container">
    <div class="col-sm-6 text-left main-description">
      <div class="form-group">
        <label class="col-sm-4 control-label">Account type</label>
        <div class="col-sm-8">
          <div class="radio">
            <%= f.radio_button :utype, 0 %> I am a professional
          </div>
          <div class="radio">
            <%= f.radio_button :utype, 1 %> I represent a company
          </div>
        </div>
      </div>
      <% if @user.visibility&&@user.visibility==1 then%>
        <p><span class="glyphicon glyphicon-play profile-play-sign" aria-hidden="true"></span>
        You profile is visible in search results
      <%else%>
        <p><span class="glyphicon glyphicon-pause profile-pause-sign" aria-hidden="true"></span>
        Your profile is hidden from search results
      <%end%>
      <div class="checkbox">
        <label>
          <%= f.check_box :visibility %> Show my profile in search results
        </label><br>
        <label>
          <%= f.check_box :stop_letters %> Unsubscribe from emails
        </label>
      </div>
      <br>
      <%= link_to "Change password", new_password_reset_path, class: "btn btn-primary" %>
      <%= check_connection('LinkedIn')%>
      <Br><br>
      <div class="form-group">
        <label class="col-sm-2 control-label">Full name</label>
        <div class="col-sm-8">
          <%= f.text_field :name, placeholder: @user.name, class: 'form-control edit-form-control' %>
        </div>
      </div>
      <%if @user.errors[:name].any?%>
        <div class="alert alert-warning"><%= @user.errors[:name].first.to_s %></div>
      <%end%>
      <div class="form-group">
        <label class="col-sm-2 control-label">Email</label>
        <div class="col-sm-8">
          <%= f.email_field :email, placeholder: @user.email, class: 'form-control edit-form-control' %>
        </div>
        <%if @user.errors[:email].any?%>
          <div class="alert alert-warning"><%= @user.errors[:email].first.to_s %></div>
        <%end%>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">Skype</label>
        <div class="col-sm-8">
          <%= f.text_field :skype, placeholder: @user.skype, class: 'form-control edit-form-control' %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-2 control-label">Phone</label>
        <div class="col-sm-8">
          <%= f.text_field :phone, placeholder: @user.phone, class: 'form-control edit-form-control' %>
        </div>
      </div>
    </div>
    <div class="col-sm-6 text-left profile-right-panel">
      <h4>Select your key skills</h4>
      <ul class="list-inline">
        <% $globalvar_skills.each do |skill|%>
          <% if @user.skills && @user.skills[skill] == "on" then checkline="checked" else checkline =""  end%>
          <li class="project-skills-edit">
            <input class="form-control" type="checkbox" name="user[skills][<%=skill%>]" id="<%=skill%>" <%=checkline%> >
            <label for="<%=skill%>"><%=skill%></label>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</div>

   
<div class="container-fluid project-container profile-public-info">
  <div class="container">
    <div class="col-sm-6 text-left main-description">
      <div class="row">
        <div class="col-sm-6">
          <% if (@user.picture && !@user.picture.empty?) %>
            <img src="<%=@user.picture%>" class="img-responsive" title="<%=@user.name%> @ The Globe." alt="<%=@user.name%> @ The Globe.">
          <%else %>
            <img src="<%=root_url + 'images/paraglide.jpg'%>" class="img-responsive">
          <%end%>
        </div>
        <div class="col-sm-6">
          
        </div>
        <div class="col-sm-12">
          <br>
          <div class="form-group">
            <label class="col-sm-4 control-label">Image</label>
            <div class="col-sm-8">
              <%= f.file_field :picture, class: 'form-control edit-form-control' %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-6 text-left profile-right-panel">
      <div class="form-group">
        <label class="col-lg-4 control-label">Resume / CV</label>
        <div class="col-lg-8">
          <%= f.file_field :resume, class: 'form-control edit-form-control' %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-4 control-label">LinkedIn</label>
        <div class="col-lg-8">
          <%= f.url_field :linkedin_link, placeholder: @user.linkedin_link, class: 'form-control edit-form-control' %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-4 control-label">Github / Behance</label>
        <div class="col-lg-8">
          <%= f.url_field :github_link, placeholder: @user.github_link, class: 'form-control edit-form-control' %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-4 control-label">Personal website or blog</label>
        <div class="col-lg-8">
          <%= f.url_field :website, placeholder: @user.website, class: 'form-control edit-form-control' %>
        </div>
      </div>
      <div class="form-group">
        <label class="col-lg-4 control-label">Location</label>
        <div class="col-lg-8">
          <%= f.text_field :location, placeholder: @user.location, class: 'form-control edit-form-control' %>
        </div>
      </div>
    
      <div class="form-group">
        <label class="col-lg-4 control-label">Citizenship, work permit, visa</label>
        <div class="col-lg-8">
          <%= f.text_field :citizenship, placeholder: @user.citizenship, class: 'form-control edit-form-control' %>
        </div>
      </div>
    </div>
    <div class="col-sm-10 col-sm-offset-1">
      <br>
      <br>
      <h2>Summary <small><sup><span class="glyphicon glyphicon-question-sign" data-toggle="tooltip" data-placement="auto" title="Things that matter for you. What kind of professional experiences are you looking for?"></span></sup></small></h2>
      <%= f.text_area :values, placeholder: "Things that matter for you. What kind of professional experiences are you looking for?", class: 'form-control edit-form-control' %>
      <h2>Experience <small><sup><span class="glyphicon glyphicon-question-sign" data-toggle="tooltip" data-placement="auto" title="Your professional experiences (include dates, position, skills and links). You may use safe html tags here."></span></sup></small></h2>
      <%= f.text_area :experience, placeholder: "Your professional experiences (include dates, position, skills and links). You may use safe html tags here.", class: 'form-control edit-form-control' %>
      <h2>Education <small><sup><span class="glyphicon glyphicon-question-sign" data-toggle="tooltip" data-placement="auto" title="Your education (include years, degree and majors/courses/skills. You may use safe html tags here."></span></sup></small></h2>
      <%= f.text_area :educ, placeholder: "Your education (include years, degree and majors/courses/skills. You may use safe html tags here.", class: 'form-control edit-form-control' %>
    </div>
    <div class="col-md-6 col-md-offset-3">
      <%= link_to 'Cancel', user_path, class:"btn btn-default" %> 
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    </div>
    <br><br>
  </div>
  
</div>
<%end%>

app/views/users/feed_business.html.erb
<% provide(:title, "The Globe. Create Anywhere.") %>
<% provide(:description, "Search for world-class pros willing to travel or relocate.") %>
<% provide(:image, root_url + "images/paraglide.jpg") %>

<div class="container-fluid project-container-header">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type%>"><%= message %></div>
  <% end %>	
  <div class="row">
    <div class="container">
      <h1>Search high profile pros</h1>
      <h3>Choose skills to browse experts that have them</h3>
      
      <%= form_tag(feed_path, method: 'get', class: "form-inline searchform") do %>
        <ul class="list-inline">
          <% $globalvar_skills.each do |skill|%>
            <li class="project-skills-edit">
              <input class="form-control" type="checkbox" name="<%=skill%>" id="<%=skill%>" <%= if @qskills[skill] then "checked" end%>>
              <label for="<%=skill%>"><%=skill%></label>
            </li>
          <%end%>
        </ul>
        <%= submit_tag "Search", class: "btn btn-lg btn-success" %>
      <%end%>
    </div>
  </div>
</div>
<div class="container-fluid project-container">
  <% if @feed!=[] then %>
    <% @feed.each do |usr| %>
    <div class="container-fluid search-public-info">
      <div class="container">
        <%= render "pro_header", usr: usr, _admin: false %>
      </div>
    </div>
    <br>
    <div class="container">
      <%= render "pro_details", usr: usr, _admin: false %>
    </div>
    <% end%>
  <% else%>
  <p>Sorry, nothing found.</p>
  <%end%>
</div>
    
    
    
  