config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: 'users/confirmations', omniauth_callbacks: "users/omniauth_callbacks" }
  

  root "static_pages#home"
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  get 'contacts', to: 'static_pages#contacts'
  get 'admin', to: 'static_pages#admin'
  get 'stats', to: 'static_pages#stats'
  
  devise_scope :user do
    get "business", to: "users/registrations#new_bus"
    get "prosignup", to: "users/registrations#new_pro"
    get 'signup', to: 'users/registrations#new_bus'
    get '/auth/facebook/callback', to: 'users/sessions#create'
    get '/users/auth/facebook/callback', to: 'users/sessions#create'
    get '/auth/linkedin/callback', to: 'users/sessions#create'
    get '/users/auth/linkedin/callback', to: 'users/sessions#create'
    get 'login', to: "users/sessions#new"
  end
  
    post 'createpassword', to:'users#createpassword'
  
  

  
  
  resources :users do
    collection do
    end
    member do
      put "like", to: "users#upvote"
      put "dislike", to: "users#downvote"
      get "offer", to: "users#newoffer"
      post "offer", to: "users#createoffer"
      get "acceptoffer", to: "users#acceptoffer"
      get "test", to: "users#new_test"
      post "test", to: "users#create_test"
      get "tests", to: "users#tests", as: :tests
      get "applications", to: "users#applications", as: :applications
    end
  end
  

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :letters, only: [:new, :create, :show]
  post 'sendletter', to: 'letters#create'
  get 'sendletter', to: 'letters#new'
  get 'automate', to: 'letters#automate_new'
  post 'automate', to: 'letters#automate_create'
  get 'automate_show', to: 'letters#automate_show'
  
  get "users/:id/edit_admin", to: "users#edit_admin", as: :edit_user_admin
  post "users/:id/mark_interviewed", to: "users#mark_interviewed", as: :user_mark_interviewed
  
  post 'users', to: 'users#index'
  get "/feed/:query", to: "users#feed"
  post "/feed/:query", to: "users#feed"
  get 'feed', to: 'users#feed'
  post 'feed', to: 'users#feed'
  

  
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get "/404", to: "errors#not_found"
  get "/500", to: "errors#internal_server_error"
  get "*path" => 'errors#not_found'
end

app/models/letter.rb
class Letter < ActiveRecord::Base
  include ActionView::Helpers::TextHelper
  serialize :skills
    
  def send_plain_mail
    UserMailer.send_plain_mail(rec, header, text).deliver_now
    
  end
  #Sends letter to 0 - all, 1 - pros, 2 - businesses, 3 - only to Irina (test)
  
  def send_mail_danger
    case self.category
    when 1
      recipients = User.where(utype: 0)
    when 2
      recipients = User.where(utype: 1)
    when 3
      recipients = User.where(id: 232)
    else
      recipients = User.all
    end
    recipients.each do |rec|
      send = true
      if self.skills && !self.skills.empty? then
        send = false
        self.skills.each do |ss|
          if rec.skills && !rec.skills.empty? && rec.skills.include?(ss[0]) then
            send = true
          end
        end
      end
      if (rec.stop_letters.to_i!=1) && (rec.id >= start_id.to_i) && send then
        puts "SEND MAIL TO " + rec.email
        UserMailer.send_mail(rec.email, rec.name, header, text).deliver_now
      end
    end
    
  end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :set_letter, only: [:show]
  http_basic_authenticate_with name: ENV['LOGIN'], password: ENV['PASSWORD'], only: [:new]
  
  def automate_new
    @letter = Letter.new
  end
  
  # POST /automate
  def automate_create
    @letterlist = parse_automate_text(letter_params[:text])
    if @letterlist && !@letterlist.empty? then
      @letterlist.each do |letter|
        letter.send_plain_mail()
        puts "letter has been saved"
      end
      render :automate_show
    else
      flash[:danger] = "The text could not be parsed"
      puts "The text could not be parsed"
      render :new
    end
  end
  
  def automate_show
  end
  
  def new
    @letter = Letter.new
  end

  # POST /letter
  def create
    @letter = Letter.new(letter_params)
    if @letter.save
      puts "letter has been saved"
      @letter.send_mail()
      flash[:success] = "Hey, we've just sent out your letter!"
      redirect_to new_letter_path
    else
      puts "letter has not been saved"
      render :new
    end
  end
  
  def show
    
    @header = @letter.header
    @text = @letter.text
    render template: 'user_mailer#send_mail'
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_letter
      puts "Set letter, id in params" + params[:id].to_s
      begin
        @letter = Letter.find(params[:id])
      rescue
       puts "Not found."
        redirect_back_or new_letter
      end
    end
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def letter_params
      params.require(:letter).permit(:header, :text, :category, :start_id, skills: $globalvar_skills)

    end
    
    
  def parse_automate_text(text)
    if !text.lines then return nil end
    list = []
    text.lines.each do |line|
      items = line.split(';')
      if items.count == 4 then
        name = items[0].gsub(/[\'\"]/,'').gsub(/\A | \z/,'')
        lookingfor = items[3].gsub(/[\'\"]/,'').gsub(/\A | \z/,'').gsub(/\r|\r\n|\n/,'')
        q = ""
        items[2].split(',').each do |skill|
          q << "&" << skill.gsub(/[\'\"]/,'').gsub(/\A | \z/,'').gsub(' ','+') << "=on"
        end
        @letter = Letter.new()
        @letter.header = "Working for " + name
        @letter.rec = items[1]
        @letter.text = "Hello<br><br>Hope this email finds you well. I noted that " + name.to_s + " is looking for " + lookingfor.to_s + ", so I wanted to introduce you to a pool of high profile web/mobile engineers from Russia and Eastern Europe willing to travel to US and around the world. What we offer is a contract at around $6k per month and up to 6 months duration with the pro travelling to your location and working in your office. Upon completion you may extend a permanent offer, continue collaborating remotely, or engage another pro &mdash; it is all up to you, we don't interfere in any way. We only charge 10% of the short-term contract. We pre-screen pros and serve as a guarantor for both sides.<br><br>Take a look at some of the profiles that may suit your needs: <a href='http://www.theglobeteam.com/feed?" + q.to_s + "&source=cmc'>http://www.theglobeteam.com/feed?" + q.to_s + "</a><br><Br>If you are willing to give it a try and with any other questions please contact me. Thank you for your time!<br><Br>Best of luck,<br>Irina Nazarova<br>CEO and co-founder<br>The Globe<br><a href='http://theglobeteam.com/?&source=cmc'>theglobeteam.com</a>"
        @letter.save
        list << @letter
      else
        puts "Wrong number of arguments"
      end
    end
    return list
    
  end
end

app/helpers/letters_helper.rb
module LettersHelper
  
end

app/views/letters/automate_new.html.erb
<% provide(:title, "Auto cold emails") %>
<br><Br>
<h1>Send a new letter</h1>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<br><br>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for @letter, url: automate_path do |f| %>
      <%= f.text_area :text, placeholder: "CompanyName, email, skills, looking_for", class: 'form-control login-form-control' %>
      <br>
      <br>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/letters/automate_show.html.erb
<br><br><bR>
  

<div class="container-fluid project-container profile-public-info">
  <div class="container">
    <div class="col-md-8 text-left">
      <%if @letterlist && !@letterlist.empty? then%>
        <% @letterlist.each do |letter|%>
          <p>To: <%= letter.rec %></p>
          <p><%= letter.header %></p>
          <br><br>
          <%= letter.text.html_safe %>
          <br>
          <hr></hr>
        <%end%>
      <%end%>
    </div>
  </div>
</div>

app/views/letters/new.html.erb
<% provide(:title, "Send a new letter to users") %>
<br><Br>
<h1>Send a new letter</h1>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<br><br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @letter, url: sendletter_path do |f| %>
      <%= f.text_field :header, placeholder: "Letter header", class: 'form-control login-form-control' %>
      <%= f.text_area :text, placeholder: "Text with html", class: 'form-control login-form-control' %>
      <input type="radio" id="letter_category_3" name="letter[category]" value="3" checked="checked" /> Self only (test)<br>
      <input type="radio" id="letter_category_0" name="letter[category]" value="0"  /> All<br>
      <input type="radio" id="letter_category_1" name="letter[category]" value="1" /> Pros only<br>
      <input type="radio" id="letter_category_2" name="letter[category]" value="2" /> Businesses only<br>
      <!--<br><p>Start id</p>
      <%= f.number_field :start_id, class: 'form-control login-form-control' %> -->
      <br>
      <p>Skill filter</p>
      <ul class="list-inline">
        <% $globalvar_skills.each do |skill|%>
          <li class="project-skills-edit">
            <input class="form-control" type="checkbox" name="letter[skills][<%=skill%>]" id="<%=skill%>" >
            <label for="<%=skill%>"><%=skill%></label>
          </li>
        <%end%>
      </ul>
      <br>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>