config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: 'users/confirmations', omniauth_callbacks: "users/omniauth_callbacks" }
  

  root "static_pages#home"
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  get 'contacts', to: 'static_pages#contacts'
  get 'admin', to: 'static_pages#admin'
  get 'stats', to: 'static_pages#stats'
  
  devise_scope :user do
    get "business", to: "users/registrations#new_bus"
    get "prosignup", to: "users/registrations#new_pro"
    get 'signup', to: 'users/registrations#new_bus'
    get '/auth/facebook/callback', to: 'users/sessions#create'
    get '/users/auth/facebook/callback', to: 'users/sessions#create'
    get '/auth/linkedin/callback', to: 'users/sessions#create'
    get '/users/auth/linkedin/callback', to: 'users/sessions#create'
    get 'login', to: "users/sessions#new"
  end
  
    post 'createpassword', to:'users#createpassword'
  
  

  
  
  resources :users do
    collection do
    end
    member do
      put "like", to: "users#upvote"
      put "dislike", to: "users#downvote"
      get "offer", to: "users#newoffer"
      post "offer", to: "users#createoffer"
      get "acceptoffer", to: "users#acceptoffer"
      get "test", to: "users#new_test"
      post "test", to: "users#create_test"
      get "tests", to: "users#tests", as: :tests
      get "applications", to: "users#applications", as: :applications
    end
  end
  

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :letters, only: [:new, :create, :show]
  post 'sendletter', to: 'letters#create'
  get 'sendletter', to: 'letters#new'
  get 'automate', to: 'letters#automate_new'
  post 'automate', to: 'letters#automate_create'
  get 'automate_show', to: 'letters#automate_show'
  
  get "users/:id/edit_admin", to: "users#edit_admin", as: :edit_user_admin
  post "users/:id/mark_interviewed", to: "users#mark_interviewed", as: :user_mark_interviewed
  
  post 'users', to: 'users#index'
  get "/feed/:query", to: "users#feed"
  post "/feed/:query", to: "users#feed"
  get 'feed', to: 'users#feed'
  post 'feed', to: 'users#feed'
  

  
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get "/404", to: "errors#not_found"
  get "/500", to: "errors#internal_server_error"
  get "*path" => 'errors#not_found'
end

app/views/layouts/_google_analytics.html.erb
<%- if Rails.env.production? %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-62899603-1', 'auto');
    ga('send', 'pageview');
  </script>
<%end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= yield :title %></title>
  
  <meta property="fb:app_id" content="1580550965555901" /> 
  <meta property="og:type"   content="website" /> 
  <meta property="og:url"    content="<%= request.original_url %>" /> 
  <meta property="og:title"  content="<%= yield :title %>" /> 
  <meta property="og:image"  content="<%= yield(:image) %>" /> 
  <meta property="og:description"  content="<%= yield(:description) %>" /> 

  <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,100,900' rel='stylesheet' type='text/css'>
  <link href="<%= root_url + 'images/favicon.ico' %>" rel="shortcut icon" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= render 'layouts/google_analytics'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="spinner" id="spinner">
			<i class="fa fa-spinner fa-pulse fa-3x fa-fw margin-bottom"></i>
			<span class="sr-only">Loading...</span>
	</div>
	<!-- Fixed navbar -->
	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to root_url, class:"navbar-brand" do %>
							  <%= image_tag('logo100.png') %>
							<% end %>
							
	    </div>
     <div id="navbar" class="collapse navbar-collapse">
      	<% if current_user %>
      		<% if current_user.utype == 0 then %>
		       <ul class="nav navbar-nav">
			        <li><%= link_to ('<span class="glyphicon glyphicon-globe" aria-hidden="true"></span> Apply to companies').html_safe, feed_url, id: "menu_feed_pro" %></li>
			        <li><%= link_to ('<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Applications').html_safe, applications_user_url(current_user), id: "menu_applications_pro" %></li>
		       </ul>
			      <ul class="nav navbar-nav navbar-right">
		        <li><%= link_to ('<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Tests').html_safe, tests_user_url(current_user), id: "menu_tests_pro" %></li>
		        <li><%= link_to (('<span class="glyphicon glyphicon-user" aria-hidden="true"></span> ').html_safe + current_user.name), current_user, class: "nav-username", id: "menu_profile_pro"%></li>
		        <li><%= link_to ('<span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit profile').html_safe, edit_user_url(current_user), id: "menu_edit_profile_pro" %></li>
		        <li><%= link_to ('<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Log out').html_safe, destroy_user_session_path, method: :delete %></li>
		       </ul>
		      <%else%>
		       <ul class="nav navbar-nav">
			        <li><%= link_to ('<span class="glyphicon glyphicon-globe" aria-hidden="true"></span> Browse pros').html_safe, feed_url, id: "menu_feed_bus" %></li>
			        <li><%= link_to ('<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Applications').html_safe, applications_user_url(current_user), id: "menu_applications_bus" %></li>
		       </ul>
			      <ul class="nav navbar-nav navbar-right">
			        <li><%= link_to (('<span class="glyphicon glyphicon-user" aria-hidden="true"></span> ').html_safe + current_user.name), current_user, class: "nav-username", id: "menu_profile_bus" %></li>
			        <li><%= link_to ('<span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit profile').html_safe, edit_user_url(current_user), id: "menu_edit_profile_bus" %></li>
			        <li><%= link_to ('<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Log out').html_safe, destroy_user_session_path, method: :delete %></li>
		       </ul>
		      <%end%>
      	<%else%>
	       <ul class="nav navbar-nav">
		        <li><%= link_to ("Find talent").html_safe, business_path, id: "menu_signup_bus" %></li>
		        <li><%= link_to ("Work overseas").html_safe, prosignup_path, id: "menu_signup_pro" %></li>
	       </ul>
		      <ul class="nav navbar-nav navbar-right">
	        <li><%= link_to ('<span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Log in').html_safe, new_user_session_path, id: "menu_login_link" %></li>
      		</ul>
      	<%end%>
	    </div>
	  </div>
	</nav>
<%= yield %>

<footer class="footer">
  <div class="container">
  	<hr></hr>
    <p>&copy; 2016 The Globe. Create Anywhere</p>
    <p>Contact us at theglobeteam @gmail.com</p>
  </div>
</footer>


</body>

</html>